AWSTemplateFormatVersion: "2010-09-09"
Description: Taurus Kolla CloudFormation template

Resources:
#   Pipeline:
#     Type: AWS::CodePipeline::Pipeline
#     Properties:
#       Name: taurus-openstack-kolla-horizon
#       RoleArn: !Ref Role
#       PipelineType: V2
#       ExecutionMode: QUEUED
#       Stages:
#         - Actions:
#           - Name: Source
#             ActionTypeId:
#               Category: Source
#               Owner: AWS
#               Provider: CodeStarSourceConnection
#               Version: '1'
#             Configuration:
#               ConnectionArn: arn:aws:codestar-connections:ap-northeast-2:664311806486:connection/a1db1898-ac72-41e1-9470-19673f910007
#               FullRepositoryId: taurus-openstack/kolla
#               BranchName: main
#               DetectChanges: false
#               OutputArtifactFormat: CODEBUILD_CLONE_REF
#             OutputArtifacts:
#               - Name: SourceArtifact
#             Region: ap-northeast-2
#             Namespace: SourceVariables
#           Name: Source
#         - Actions:
#           - Name: Build
#             ActionTypeId:
#               Category: Build
#               Owner: AWS
#               Provider: CodeBuild
#               Version: '1'
#             Configuration:
#               ProjectName: taurus-openstack-kolla
#               EnvironmentVariables: [
#                  {
#                     "name":"OS_PROJECT",
#                     "value":"horizon",
#                     "type":"PLAINTEXT"
#                  },
#                  {
#                     "name":"OS_REGISTRY_URL",
#                     "value":"public.ecr.aws/p6g9k8e4",
#                     "type":"PLAINTEXT"
#                  },
#                  {
#                     "name":"OS_RELEASE",
#                     "value":"2024.1",
#                     "type":"PLAINTEXT"
#                  },
#                  {
#                     "name":"OS_CUSTOM_TAG",
#                     "value":"taurus",
#                     "type":"PLAINTEXT"
#                  }
#               ]
#             InputArtifacts:
#               - Name: SourceArtifact
#             OutputArtifacts:
#               - Name: BuildArtifact
#             Region: ap-northeast-2
#             Namespace: BuildVariables
#           Name: Build

  Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: codepipeline-taurus-openstack-kolla-role
      AssumeRolePolicyDocument: {
          "Version": "2012-10-17",
          "Statement": [
              {
                  "Effect": "Allow",
                  "Principal": {
                      "Service": "codepipeline.amazonaws.com"
                  },
                  "Action": "sts:AssumeRole"
              }
          ]
      }
      Policies: 
      - PolicyName: AWSCodePipelineServiceRole
        PolicyDocument: {
            "Statement": [
                {
                    "Action": [
                        "iam:PassRole"
                    ],
                    "Resource": "*",
                    "Effect": "Allow",
                    "Condition": {
                        "StringEqualsIfExists": {
                            "iam:PassedToService": [
                                "cloudformation.amazonaws.com",
                                "elasticbeanstalk.amazonaws.com",
                                "ec2.amazonaws.com",
                                "ecs-tasks.amazonaws.com"
                            ]
                        }
                    }
                },
                {
                    "Action": [
                        "codecommit:CancelUploadArchive",
                        "codecommit:GetBranch",
                        "codecommit:GetCommit",
                        "codecommit:GetRepository",
                        "codecommit:GetUploadArchiveStatus",
                        "codecommit:UploadArchive"
                    ],
                    "Resource": "*",
                    "Effect": "Allow"
                },
                {
                    "Action": [
                        "codedeploy:CreateDeployment",
                        "codedeploy:GetApplication",
                        "codedeploy:GetApplicationRevision",
                        "codedeploy:GetDeployment",
                        "codedeploy:GetDeploymentConfig",
                        "codedeploy:RegisterApplicationRevision"
                    ],
                    "Resource": "*",
                    "Effect": "Allow"
                },
                {
                    "Action": [
                        "codestar-connections:UseConnection"
                    ],
                    "Resource": "*",
                    "Effect": "Allow"
                },
                {
                    "Action": [
                        "elasticbeanstalk:*",
                        "ec2:*",
                        "elasticloadbalancing:*",
                        "autoscaling:*",
                        "cloudwatch:*",
                        "s3:*",
                        "sns:*",
                        "cloudformation:*",
                        "rds:*",
                        "sqs:*",
                        "ecs:*"
                    ],
                    "Resource": "*",
                    "Effect": "Allow"
                },
                {
                    "Action": [
                        "lambda:InvokeFunction",
                        "lambda:ListFunctions"
                    ],
                    "Resource": "*",
                    "Effect": "Allow"
                },
                {
                    "Action": [
                        "opsworks:CreateDeployment",
                        "opsworks:DescribeApps",
                        "opsworks:DescribeCommands",
                        "opsworks:DescribeDeployments",
                        "opsworks:DescribeInstances",
                        "opsworks:DescribeStacks",
                        "opsworks:UpdateApp",
                        "opsworks:UpdateStack"
                    ],
                    "Resource": "*",
                    "Effect": "Allow"
                },
                {
                    "Action": [
                        "cloudformation:CreateStack",
                        "cloudformation:DeleteStack",
                        "cloudformation:DescribeStacks",
                        "cloudformation:UpdateStack",
                        "cloudformation:CreateChangeSet",
                        "cloudformation:DeleteChangeSet",
                        "cloudformation:DescribeChangeSet",
                        "cloudformation:ExecuteChangeSet",
                        "cloudformation:SetStackPolicy",
                        "cloudformation:ValidateTemplate"
                    ],
                    "Resource": "*",
                    "Effect": "Allow"
                },
                {
                    "Action": [
                        "codebuild:BatchGetBuilds",
                        "codebuild:StartBuild",
                        "codebuild:BatchGetBuildBatches",
                        "codebuild:StartBuildBatch"
                    ],
                    "Resource": "*",
                    "Effect": "Allow"
                },
                {
                    "Effect": "Allow",
                    "Action": [
                        "devicefarm:ListProjects",
                        "devicefarm:ListDevicePools",
                        "devicefarm:GetRun",
                        "devicefarm:GetUpload",
                        "devicefarm:CreateUpload",
                        "devicefarm:ScheduleRun"
                    ],
                    "Resource": "*"
                },
                {
                    "Effect": "Allow",
                    "Action": [
                        "servicecatalog:ListProvisioningArtifacts",
                        "servicecatalog:CreateProvisioningArtifact",
                        "servicecatalog:DescribeProvisioningArtifact",
                        "servicecatalog:DeleteProvisioningArtifact",
                        "servicecatalog:UpdateProduct"
                    ],
                    "Resource": "*"
                },
                {
                    "Effect": "Allow",
                    "Action": [
                        "cloudformation:ValidateTemplate"
                    ],
                    "Resource": "*"
                },
                {
                    "Effect": "Allow",
                    "Action": [
                        "ecr:DescribeImages"
                    ],
                    "Resource": "*"
                },
                {
                    "Effect": "Allow",
                    "Action": [
                        "states:DescribeExecution",
                        "states:DescribeStateMachine",
                        "states:StartExecution"
                    ],
                    "Resource": "*"
                },
                {
                    "Effect": "Allow",
                    "Action": [
                        "appconfig:StartDeployment",
                        "appconfig:StopDeployment",
                        "appconfig:GetDeployment"
                    ],
                    "Resource": "*"
                }
            ],
            "Version": "2012-10-17"
        }
